### PR TITLE
Rate limit issue fix

### PR DESCRIPTION
**Pull request by Scunl**
I fixed the issue of "rate limit". Here is how you use toutatis:
`cd toutatis`
`toutatis -u USERNAME -s SESSIONID -i USERID`

You can find user id by looking on this website: https://commentpicker.com/instagram-user-id.php

Good luck !

### CODE REVIEW

**Comment by Creepy2e** [comment]
> cd toutatis

PgoMw -i 54158219241
usage: toutatis [-h] -s SESSIONID -u USERNAME
toutatis: error: unrecognized arguments: -i 54158219241

**Comment by Scunl** [comment]
@Creepy2e here ? u can download my code no ?

**Comment by Creepy2e** [comment]
> @Creepy2e here ? u can download my code no ?

i have copy this code but i get the same error:

 **usage: toutatis [-h] -s SESSIONID -u USERNAME
toutatis: error: unrecognized arguments: -i 54158219241**

**Comment by Scunl** [comment]
add me on discord: scunl

**Comment by nowt46** [comment]
Still same error...toutatis: error: unrecognized arguments: -i 65215828351

**Comment by Scunl** [comment]
'pip uninstall toutatis' and run mine

**Comment by TheGanjalord** [comment]
> 'pip uninstall toutatis' and run mine

can yours be installed with pip? If not how do I run it exactly? Sorry I am very stupid

**Comment by dajohnj** [comment]
im also having some issues can anyone provide me with a step by step guide?
pip install toutatis and now what

**Comment by SimonCoulombe** [comment]
works for me. 
installed using this command
pip install  "git+https://github.com/megadose/toutatis@refs/pull/97/head"

**Pull request closed without merging**
